config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "recipes#index", as: "home"

  resources :recipes
  resources :users, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id          :integer          not null, primary key
#  name        :string
#  recipe_type :string
#  ingredients :string           is an Array
#  directions  :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#
# Indexes
#
#  index_recipes_on_user_id  (user_id)
#

class Recipe < ApplicationRecord
  belongs_to(
    :creator,
    class_name: "User",
    foreign_key: "user_id",
    inverse_of: :recipes,
    optional: :true
  )

  has_many(
    :recipe_tags,
    class_name: "RecipeTag",
    foreign_key: "recipe_id",
    inverse_of: :recipe,
    dependent: :destroy
  )

  has_many :tags, through: :recipe_tags

  validates :name, presence: true
  validates :recipe_type, presence: true
  validates :ingredients, presence: true
  validates :directions, presence: true

  validate :validate_ingredients_array

  private

  def validate_ingredients_array
    if ingredients.blank? || !ingredients.is_a?(Array) || ingredients.any? { |i| !i.is_a?(String) }
      errors.add(:ingredients, "Recipe ingredients must be a non-empty array of strings")
    end
  end
end

app/models/recipe_tag.rb
# == Schema Information
#
# Table name: recipe_tags
#
#  id         :integer          not null, primary key
#  recipe_id  :integer          not null
#  tag_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_recipe_tags_on_recipe_id  (recipe_id)
#  index_recipe_tags_on_tag_id     (tag_id)
#

class RecipeTag < ApplicationRecord
  belongs_to(
    :recipe,
    class_name: "Recipe",
    foreign_key: "recipe_id",
    inverse_of: :recipe_tags
  )

  belongs_to(
    :tag,
    class_name: "Tag",
    foreign_key: "tag_id",
    inverse_of: :recipe_tags
  )
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  color      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
  has_many(
    :recipe_tags,
    class_name: "RecipeTag",
    foreign_key: "tag_id",
    inverse_of: :tag,
    dependent: :destroy
  )

  has_many :recipes, through: :recipe_tags

  validates :name, presence: true
  validates :color, presence: true

  validate :validate_color_format

  private

  def validate_color_format
    unless color.match?(/\A#(?:[0-9a-fA-F]{3}){1,2}\z/)
      errors.add(:color, "Tag color must be in the valid hexcode format (e.g. #054FCA)")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many(
    :recipes,
    class_name: "Recipe",
    foreign_key: "user_id",
    inverse_of: :creator
  )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [ :index ]

  def index
    @recipes = Recipe.order(:name)

    # Keyword seaches a specific filter
    if params[:search].present? && params[:filter].present?
      case params[:filter]
      when "Name"
        @recipes = @recipes.where("recipes.name ILIKE ?", "%#{params[:search]}%")
      when "Ingredients"
        @recipes = @recipes.where("recipes.ingredients::text ILIKE ?", "%#{params[:search]}%")
      when "Tag"
        @recipes = @recipes.joins(:tags).where("tags.name ILIKE ?", "%#{params[:search]}%")
      end

    # Filters recipes to require all tags queried when not searching
    elsif params[:tag_ids].present?
      tag_ids = params[:tag_ids].split(",").map(&:to_i)
      @tags = Tag.where(tags: { id: tag_ids })
      @recipes = @recipes
        .joins(:tags)
        .where(tags: { id: tag_ids })
        .group("recipes.id")
        .having("COUNT(tags.id) = ?", tag_ids.size)
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @tags = Tag.all.sort_by { |tag| @recipe.tags.include?(tag) ? 0 : 1 }
  end

  def new
    @recipe = Recipe.new
    @tags = Tag.all
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:alert] = "The recipe was successfully deleted."
    redirect_to user_path(current_user), status: :see_other
  end

  def create
    parameters = params.require(:recipe).permit(:name, :recipe_type, :ingredients, :directions, tag_ids: [])

    # Sanitize input parameters
    parameters[:name] = sanitize_example(params[:recipe][:name])
    parameters[:ingredients] = sanitize_example(params[:recipe][:ingredients]).to_s.split("\n").map(&:strip).reject(&:empty?)
    parameters[:directions] = sanitize_example(params[:recipe][:directions])

    @recipe = current_user.recipes.new(parameters)
    if @recipe.save
      flash[:success] = "New recipe successfully added!"
      redirect_to user_path(current_user)
    else
      @tags = Tag.all.sort_by { |tag| @recipe.tags.include?(tag) ? 0 : 1 }
      flash.now[:error] = "Recipe creation failed"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    parameters = params.require(:recipe).permit(:name, :recipe_type, :ingredients, :directions, tag_ids: [])

    # Sanitize input parameters
    parameters[:name] = sanitize_example(params[:recipe][:name])
    parameters[:ingredients] = sanitize_example(params[:recipe][:ingredients]).to_s.split("\n").map(&:strip).reject(&:empty?)
    parameters[:directions] = sanitize_example(params[:recipe][:directions])

    if @recipe.update(parameters)
      flash[:notice] = "Recipe successfully updated!"
      redirect_to user_path(current_user)
    else
      @tags = Tag.all.sort_by { |tag| @recipe.tags.include?(tag) ? 0 : 1 }
      flash.now[:error] = "Recipe update failed"
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def sanitize_example(input)
    # Matches JavaScript tags and removes them along with their content
    input.gsub(/<script.*?>.*?<\/script>/im, "")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
    @recipes = @user.recipes()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    if request.path == path
      "active"
    else
      ""
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  # Adds/removes tag_ids for querying
  def toggle_tag_in_params(tag_id)
    current_tags = params[:tag_ids] || []
    current_tags = current_tags.is_a?(String) ? current_tags.split(",") : current_tags.map(&:to_s)

    if current_tags.include?(tag_id.to_s)
      # Removes the tag
      current_tags.delete(tag_id.to_s)
    else
      # Adds the tag
      current_tags << tag_id.to_s
    end

    # Returns the query parameters
    { tag_ids: current_tags.any? ? current_tags.join(",") : nil }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_default_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body mb-4">
  <div class="container-fluid">
  <!-- Home Button -->
    <%= link_to "Home", home_path, class: "navbar-brand ms-3 me-3"%>
  <!-- Collapsable -->
    <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
    <!-- Navigation Buttons -->
      <ul class="navbar-nav ms-3 me-auto">
        <li class="nav-item me-2"><%= link_to "Cocktails", recipes_path, class: "nav-btn" %></li>
      </ul>
  <!-- Sign in/out -->
    <ul class="navbar-nav me-4">
    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to "Profile", user_path(current_user), class: "nav-link #{active_class(edit_user_registration_path)} btn btn-link" %></li>
      <li class="nav-item"><%= button_to 'Sign Out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'nav-link btn btn-link' %></li>
    <% else %>
      <li class="nav-item"><%= link_to 'Sign In', new_user_session_path, class: "nav-link #{active_class(new_user_session_path)} btn btn-link" %></li>
      <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class: "nav-link #{active_class(new_user_registration_path)} btn btn-link" %></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<% if controller_name == "recipes" && action_name == "index" %>
  <%= render "layouts/navbar_with_filters", tags: tags %>
<% else %>
  <%= render "layouts/default_navbar" %>
<% end %>

app/views/layouts/_navbar_with_filters.html.erb
<nav class="navbar navbar-expand-lg bg-body mb-5">
  <div class="container-fluid">
  <!-- Home Button -->
    <%= link_to "Home", home_path, class: "navbar-brand ms-3 me-3"%>
  <!-- Collapsable -->
    <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
    <!-- Navigation Buttons -->
      <ul class="navbar-nav ms-3 me-5">
        <li class="nav-item me-2"><%= link_to "Cocktails", recipes_path, class: "nav-btn" %></li>
      </ul>
    <!-- Tags -->
      <ul class="nav-filters navbar-nav me-auto">
      <% if @tags %>
      <span class="navbar-text ms-1 me-1">Filtering by: </span>
        <% @tags.each do | tag | %>
          <li class="nav-item align-content-center"><%= link_to "#{tag.name}", "#{recipes_path(toggle_tag_in_params(tag.id))}", class: "nav-btn-tag ms-1 me-1", style: "background-color: #{tag.color}; border-color: #{tag.color}" %></li>
        <% end %>
      <% end %>
      </ul>
    <!-- Search Bar & Btns -->
      <div class="d-flex ms-5 me-5 justify-content-end">
        <%= form_with url: recipes_path, method: :get, class: "d-flex" do %>
        <!-- Filter Button -->
          <div class="btn-group dropdown">
            <%= button_tag params[:filter] ? params[:filter] : "Search By: ", id: "filterButton", class: "nav-btn dropdown-toggle ms-1 me-1", type: "button", data: { bs_toggle: "dropdown" } %>
            <ul class="dropdown-menu">
              <li><%= link_to "Name", "#", class: "dropdown-item", onclick: "updateFilter('Name')" %></li>
              <li><%= link_to "Tag", "#", class: "dropdown-item", onclick: "updateFilter('Tag')" %></li>
              <li><%= link_to "Ingredient", "#", class: "dropdown-item", onclick: "updateFilter('Ingredients')" %></li>
            </ul>
            <%= hidden_field_tag :filter, params[:filter], id: "filterBy" %>
          </div>
        <!-- Search Bar & Buttons -->
          <input class="search ms-1 me-1" value="<%= params[:search] %>" type="search" name="search" placeholder="Search" aria-label="Search">
          <button class="nav-search-btn ms-1 me-1">Search</button>
          <%= link_to "Reset", recipes_path, class: "nav-reset-btn ms-1 me-1", type: "button" %>
        <% end %>
      </div>
    </div>
  <!-- Sign in/out -->
    <ul class="navbar-nav me-4">
    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to "Profile", user_path(current_user), class: "nav-link #{active_class(edit_user_registration_path)} btn btn-link" %></li>
      <li class="nav-item"><%= button_to 'Sign Out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'nav-link btn btn-link' %></li>
    <% else %>
      <li class="nav-item"><%= link_to 'Sign In', new_user_session_path, class: "nav-link #{active_class(new_user_session_path)} btn btn-link" %></li>
      <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class: "nav-link #{active_class(new_user_registration_path)} btn btn-link" %></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Digital Recipe Book" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <!-- Includes all stylesheet files in app/assets/stylesheets -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Flash Messages  -->
      <div class="flash-container position-fixed top-0 start-50 translate-middle-x mt-3">
        <% flash.each do |type, message| %>
          <% bootstrap_class = case type.to_sym
            when :notice then "primary"
            when :alert then "danger"
            when :error then "danger"
            when :success then "success"
            when :warning then "warning"
            when :info then "info"
            else "primary"
          end %>

          <div class="alert alert-<%= bootstrap_class %> alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
      </div>

    <!-- Main Layout -->
      <main role="main" class="container-fluid">
        <%= render partial: "layouts/navbar", locals: { tags: @tags } %>
        <%= yield %>
      </main>
  </body>
</html>

app/views/recipes/edit.html.erb
<div class="container" style="max-width: 50%;">
  <h1>Edit Recipe</h1>
  <%= form_with model: @recipe, url: recipe_path, method: :patch do |form| %>
    <!-- Name -->
      <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      
    <!-- Recipe Type -->
      <%= form.hidden_field :recipe_type, value: :cocktail %>

    <!-- Tags -->
      <div class="row row-cols-auto mb-3">
        <%= form.label :tag_ids, "Tags" %>
        <div class="form-check" style="max-height: 120px; overflow-y: auto;">
          <%= form.collection_check_boxes :tag_ids, @tags, :id, :name do |box| %>
            <div class="col-2 form-check form-check-inline">
              <%= box.check_box(class: "form-check-input") %>
              <%= box.label(class: "form-check-label") %>
            </div>
          <% end %>
        </div>
      </div>

    <!-- Ingredients -->
      <div class="mb-3">
        <%= label_tag :ingredients, "Ingredients (one per line)", class: "form-label" %>
        <%= text_area_tag "recipe[ingredients]", @recipe.ingredients&.join("\n"), class: "form-control", rows: 4 %>
      </div>

    <!-- Direcitons -->
      <div class="mb-3">
        <%= form.label :directions, "Directions", class: "form-label" %>
        <%= form.text_area :directions, class: "form-control", rows: 4 %>
      </div>

    <!-- Update and Destroy Btns -->
      <div class="d-flex justify-content-between align-items-center mt-4">
        <%= form.submit "Update Recipe", class: "create-btn" %>
    <% end %>
        <%= form_with(model: @recipe, method: :delete, html: { onsubmit: "return confirm('Are you sure you want to delete this recipe?');", class: "d-inline" }) do %>
          <%= submit_tag "Delete Recipe", class: "delete-btn" %>
        <% end %>
      </div>
</div>

app/views/recipes/index.html.erb
<!-- Recipes -->
<div class="container">
  <div class="row row-cols-auto justify-content-center">
  <% @recipes.each do | recipe | %>
    <div class="col mb-4">
      <div class="recipe-card shadow p-4 bg-body rounded h-100 w-100">
        <!-- Creator Label -->
          <% if recipe.creator %>
            <div class="label position-absolute top-0 end-0 m-2">
              Created by: <%= recipe.creator.email.split('@').first.titleize %>
            </div>
          <% end %>
        <div class="card-body">
          <h2 class="card-title" style="margin-bottom: .25rem;"><%= recipe.name %></h2>
          <!-- Tags -->
            <div>
            <% recipe.tags.each do | tag | %>
              <%= link_to "#{tag.name}", "#{recipes_path(toggle_tag_in_params(tag.id))}", class: "btn-tag", style: "background-color: #{tag.color}; border-color: #{tag.color}" %>
            <% end %>
            </div>
          <!-- Ingredients -->
            <h5 class="card-text">Ingredients</h5>
            <ul>
              <% recipe.ingredients.each do | ingredient | %>
                <li><p class="card-text"><%= ingredient %></p></li>
              <% end %>
            </ul>
          <!-- Directions -->
            <h5 class="card-text">Directions</h5>
            <div>
              <% directions = recipe.directions.split("\n") %>
              <% directions.each do | direction | %>
                <p class="card-text" style="margin: 0; padding: 0;"><%= direction %></p>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

<script>
  // Changes the text in the filter button to match it's value
  function updateFilter(input) {
    let filterButton = document.getElementById("filterButton")
    let filterInput = document.getElementById("filterBy")

    filterButton.textContent = input
    filterInput.value = input
  }

</script>

app/views/recipes/new.html.erb
<div class="container" style="max-width: 50%;">
  <h1>Create Recipe</h1>
  <%= form_with model: @recipe, url: recipes_path, method: :post do |form| %>
    <!-- Name -->
      <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

    <!-- Recipe Type -->
      <%= form.hidden_field :recipe_type, value: :cocktail %>

    <!-- Tags -->
      <div class="row row-cols-auto mb-3">
        <%= form.label :tag_ids, "Tags" %>
        <div class="form-check" style="max-height: 120px; overflow-y: auto;">
          <%= form.collection_check_boxes :tag_ids, @tags, :id, :name do |box| %>
            <div class="col-2 form-check form-check-inline">
              <%= box.check_box(class: "form-check-input") %>
              <%= box.label(class: "form-check-label") %>
            </div>
          <% end %>
        </div>
      </div>

    <!-- Ingredients -->
      <div class="mb-3">
        <%= label_tag :ingredients, "Ingredients (one per line)", class: "form-label" %>
        <%= text_area_tag "recipe[ingredients]", @recipe.ingredients&.join("\n"), class: "form-control", rows: 4 %>
      </div>

    <!-- Directions -->
      <div class="mb-3">
        <%= form.label :directions, "Directions", class: "form-label" %>
        <%= form.text_area :directions, class: "form-control", rows: 4 %>
      </div>

    <!-- Create Button -->
      <div class="d-flex justify-content-between align-items-center mt-4">
        <%= form.submit "Create Recipe", class: "btn btn-success" %>
      </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="d-inline-flex justify-content-center mb-4">
    <h2>Your Recipes</h2>
    <%= link_to 'Create New Recipe', new_recipe_path, class: 'create-btn ms-3' %>
  </div>
  <div class="row row-cols-auto justify-content-center">
  <% @recipes.each do | recipe | %>
    <div class="col mb-4">
      <%= link_to edit_recipe_path(recipe), class: 'edit-card-btn' do %>
        <div class="card shadow p-4 bg-body rounded h-100 w-100">
          <div class="card-body">
            <div class="label position-absolute top-0 end-0 m-2">Edit</div>
            <h2 class="card-title" style="margin-bottom: .25rem;"><%= recipe.name %></h2>
            <!-- Tags -->
              <% recipe.tags.each do | tag | %>
                <div class="tag" style="background-color: <%= tag.color %>; border-color: <%= tag.color %>"><%= tag.name %></div>
              <% end %>
            <!-- Ingredients -->
              <h5 class="card-text">Ingredients</h5>
              <ul>
                  <% recipe.ingredients.each do | ingredient | %>
                  <li><p class="card-text"><%= ingredient %></p></li>
                  <% end %>
              </ul>
            <!-- Directions -->
              <h5 class="card-text">Directions</h5>
              <div>
                  <% directions = recipe.directions.split("\n") %>
                  <% directions.each do | direction | %>
                  <p class="card-text" style="margin: 0; padding: 0;"><%= direction %></p>
                  <% end %>
              </div>

          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  </div>
</div>